version: "3"
services:
    test:
        container_name: e2e-test
        build:
            context: .
            dockerfile: ./Dockerfile
        links:
            - chrome
        volumes:
            - ".:/usr/local/app"
    selenium-hub:
        image: selenium/hub:3.12.0-cobalt
        container_name: selenium-hub
        ports:
            - "4444:4444"
    chrome:
        image: selenium/node-chrome:3.12.0-cobalt
        links:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
